#!/usr/bin/env node
// Generate src/version.ts from package.json "version".
//
// HOST_VERSION is part of the transpile-cache key (see src/cache.ts): bumping
// the package version invalidates every cached transpile output, which is what
// we want — a new @actcore/web-runtime release may carry new transpiler patches or a
// new bundled jco/bindgen, so previously-cached artifacts must not be reused.
//
// Wired into `npm run build` so the constant can never drift from package.json.
// The file is also committed so a fresh checkout typechecks without a build.

import { readFile, writeFile } from 'node:fs/promises';

const pkgUrl = new URL('../package.json', import.meta.url);
const outUrl = new URL('../src/version.ts', import.meta.url);

const pkg = JSON.parse(await readFile(pkgUrl, 'utf8'));
const version = pkg.version;
if (typeof version !== 'string' || version.length === 0) {
  throw new Error('package.json has no "version" string');
}

const out =
  `// @generated by scripts/gen-version.mjs — do not edit by hand.\n` +
  `// Mirrors package.json "version". Part of the transpile-cache key, so a\n` +
  `// version bump deliberately invalidates all cached transpile output.\n` +
  `export const HOST_VERSION = ${JSON.stringify(version)};\n`;

await writeFile(outUrl, out, 'utf8');
console.log(`wrote src/version.ts: HOST_VERSION = ${version}`);
