// @generated by scripts/gen-version.mjs — do not edit by hand.
// Mirrors package.json "version". Part of the transpile-cache key, so a
// version bump deliberately invalidates all cached transpile output.
export const HOST_VERSION = "0.1.1";
